/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structures.and.algorithms;

public class App {
    public String getGreeting() {

        return "";
    }


    static final LinkedList<Integer> list1 = new LinkedList<>();
    static final LinkedList<Integer> list2 = new LinkedList<>();
    static final LinkedList<Integer> list3 = new LinkedList<>();

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        list1.insert(7);
        list1.insert(9);
        list1.insert(5);
        list1.insert(20);

//        list1.insert(10);
//        list1.insert(8);
//        list1.insert(20);
//        list1.insert(14);

        System.out.println("Does your value exist ? " + list1.include(5));
        System.out.println("Does your value exist ? " + list1.include(25));
        System.out.println(list1.toString());
//        System.out.println(list1.Append(5));
        System.out.println(list1.insertBefore(9 , 11));
        System.out.println(list1);
        System.out.println(list1.insertAfter(9 , 11));
        System.out.println(list1);
        list1.kthFromEnd(15);
        list2.getHeadValue();
        list2.getLastValue();

        System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");


        LinkedList llist1 = new LinkedList();
        LinkedList llist2 = new LinkedList();
        llist1.Append(5);
        llist1.Append(0);
        llist1.Append(4);

        System.out.println("First Linked List:");
        System.out.println(llist1.toString());

        llist2.Append(6);
        llist2.Append(4);
        llist2.Append(2);
        llist2.Append(0);
        llist2.Append(9);
        llist2.Append(8);

        System.out.println("Second Linked List:");
        System.out.println(llist2.toString());

        System.out.println("merged  linked list:");

        System.out.println(list3.ziplists( llist1 , llist2));





    }
}