/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structures.and.algorithms;

public class App {
    public String getGreeting() {

        return "";
    }


    static final LinkedList<Integer> list1 = new LinkedList<>();
    static final LinkedList<Integer> list2 = new LinkedList<>();

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        list1.insert(7);
        list1.insert(9);
        list1.insert(5);
        list1.insert(20);

        System.out.println("Does your value exist ? " + list1.include(5));
        System.out.println("Does your value exist ? " + list1.include(25));
        System.out.println(list1.toString());
//        System.out.println(list1.Append(5));
        System.out.println(list1.insertBefore(9 , 11));
        System.out.println(list1);
        System.out.println(list1.insertAfter(9 , 11));
        System.out.println(list1);

    }
}